//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace configtool.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langres_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langres_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("configtool.Lang.langres_en", typeof(langres_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase device.
        /// </summary>
        internal static string erase {
            get {
                return ResourceManager.GetString("erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from device.
        /// </summary>
        internal static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters table is empty.
        /// </summary>
        internal static string msgCfgEmpty {
            get {
                return ResourceManager.GetString("msgCfgEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration loaded.
        /// </summary>
        internal static string msgCfgLoaded {
            get {
                return ResourceManager.GetString("msgCfgLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong checksum, communication error.
        /// </summary>
        internal static string msgChksum {
            get {
                return ResourceManager.GetString("msgChksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device erased.
        /// </summary>
        internal static string msgErased {
            get {
                return ResourceManager.GetString("msgErased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data.
        /// </summary>
        internal static string msgMissingData {
            get {
                return ResourceManager.GetString("msgMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not configured.
        /// </summary>
        internal static string msgNotCfg {
            get {
                return ResourceManager.GetString("msgNotCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template for version ID={0} product ID={1}.
        /// </summary>
        internal static string msgNoTempl {
            get {
                return ResourceManager.GetString("msgNoTempl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout, device not responding.
        /// </summary>
        internal static string msgNotResp {
            get {
                return ResourceManager.GetString("msgNotResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration sent.
        /// </summary>
        internal static string msgSent {
            get {
                return ResourceManager.GetString("msgSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to device.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string tblDescCol {
            get {
                return ResourceManager.GetString("tblDescCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string tblParamCol {
            get {
                return ResourceManager.GetString("tblParamCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string tblValueCol {
            get {
                return ResourceManager.GetString("tblValueCol", resourceCulture);
            }
        }
    }
}
